package com.uk.aisl.guidewire.shredder.designer;

public class Printer {

	public static void printTheShredder() {
		System.out.println("                                                               " + System.lineSeparator()
				+ "                THE SHREDDER RETURNS IN                                 " + System.lineSeparator()
				+ "             Teenage Mutant Ninja Turtles:                              " + System.lineSeparator()
				+ "                      XM-HELL                                           " + System.lineSeparator()
				+ "                                                                        " + System.lineSeparator()
				+ "                    .;iiiiii;;.                                         " + System.lineSeparator()
				+ "                ;i!!!!!!!!!!!!!!!i.                                     " + System.lineSeparator()
				+ "             .i!!!!!!!!!'`.......`''=                                   " + System.lineSeparator()
				+ "            i!!!!!!!!' .:::::::::::::..                                 " + System.lineSeparator()
				+ "           i!!!!!!!!' :::::::::::::::::::.                              " + System.lineSeparator()
				+ "        ' i!!!!!!!!' :::::::::::::::::::::::.                           " + System.lineSeparator()
				+ "       :  !!!!!!!!! ::::::::::::::::::::::::::.                         " + System.lineSeparator()
				+ "      ::  !!!!!!!! ::::::::::::::::::::::::::::::                       " + System.lineSeparator()
				+ "     ::: <!!!!!!!! ::::::::::::::::::::::::::::::: i!!!!>               " + System.lineSeparator()
				+ "    .::: <!!!!!!!> ::::::::::::::::::::::::::::'` i!!!!!'               " + System.lineSeparator()
				+ "    :::: <!!!!!!!> ::::::::::::::::::::::::'`  ,i!!!!!!'                " + System.lineSeparator()
				+ "    :::: `!!!!!!!> :::::::::::::::::::''`  ,i!!!!!!!!'..                " + System.lineSeparator()
				+ "   `::::  !!!!!!!!.`::::::::::::::'` .,;i!!!!!!!!!!' ::::.              " + System.lineSeparator()
				+ "    ::::  !!!!!!!!!, `''''```  .,;ii!!!!!!!!!!!'' .::::::::             " + System.lineSeparator()
				+ "i!; `::' .!!!!!!!!!!!i;,;i!!!!!!!!!!!!!!!!!!' .::::::::::::::           " + System.lineSeparator()
				+ "i!!!!i;,;i!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!''`  ::::::::::::::::::         " + System.lineSeparator()
				+ "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'`..euJB$. ::::::::::::::::' ::.     " + System.lineSeparator()
				+ "!!!!!!!!!!!!!!!!!!!!!!!!!!!''`,   $$$$$$$$$Fc :::::::::::::: .:::::     " + System.lineSeparator()
				+ "  `''''''''''''''''` ..z e$$$F   d$P*`**??<<3c :::::::::::' ::::::::.   " + System.lineSeparator()
				+ "     :::: ?Fx$b. *?$ $$$b($$*   dF   'ud$$$$$$c `:::::::' .:::::::::::  " + System.lineSeparator()
				+ "     `:::  $$$$$r-.  P9$$$?$bedE' .,d$$$$$$$P*   `::::' .:::::::::::::  " + System.lineSeparator()
				+ "      :::: `? =       ****   **?????????**  .~~~.  :'.:::::::::::::::' ;" + System.lineSeparator()
				+ "      :::::  $$$eeed* .~~~~~~~~~~~~~~~~~~~~~~~~~~~  ::::::::::::::::' i!" + System.lineSeparator()
				+ "      :::::  $$$PF* .~~.$.~~~~~~~~~~~~~~~~~~~~~~~~.  :::::::::::::' ,!!!" + System.lineSeparator()
				+ "       ::       .~~~~~~ ?$ ~~~~~~~~~~~~~~~~~~~~~~~~.  ::::::::::'  ;!!!!" + System.lineSeparator()
				+ "        ::  ~~~~~~~~~~~.`$b ~~~~~~~~~~~~~~~~~~~~~~~~. `:::::::'  ;!!!!!'" + System.lineSeparator()
				+ "       `:::  ~~~~~~~~~~~ `$L ~~~~~~~~~~~~~~~~~~~~~~~ .  `''`   ;!!!!!!  " + System.lineSeparator()
				+ "        ::::  ~~~~~~~~~~~ `$c'~~~~~~~~~~~~~~~~~~~~~ ~~ ,iiii! i!!!!!!  !" + System.lineSeparator()
				+ "        :::::  ~~~~~~~~~~~ *$c`~~~~~~~~~~~~~~~~~~~ ~~ ;!!!!' i!!!!!!  i!" + System.lineSeparator()
				+ "        `:::::  ~~~~~~~~~~~ `$.`~~~~~~~~~~~~~~~~  ~  <!!!!' ;!!!!!!'  !!" + System.lineSeparator()
				+ "         :::'`   `~~~~~~~~~~ *$.`~~~~~~~~~~~~~~ .~ .!!!!!' ;!!!!!!!  i!!" + System.lineSeparator()
				+ "            ,i!    ~~~~~~~~~~ *$r'~~~~~~~~~~~~ '  ;!!!!!  ;!!!!!!!!  !!!" + System.lineSeparator()
				+ "           !!!!i !i. `~~~~~~~~ `$c ~~~~~~~~~~~~  <!!!!'  i!!!!!!!!!  !!!" + System.lineSeparator()
				+ "           :!!!!> !!!;  ~~~~~~~. *$. ~~~~~~~~ .;!!!!'  ;!!!!!!!';!!  `!!" + System.lineSeparator()
				+ "           `!!!!! `!!!!;.  ~~~~~~~~~~~~~~  .;i!!!!' .i!!!!!!' ,!!!!i  !!" + System.lineSeparator()
				+ "            !!!!!!; `!!!!!i;. ~~~~~~~ .;i!!!!''`.;i!!!!!!!'.;!!!!!!!>  !" + System.lineSeparator()
				+ "        :!  !!!!!!!i `'!!!!!!!!!!!!!!!'''`.;ii!!!!!'`.'` ;!!!!!!!!!!   '");
	}

}
